version: "3"
services:
  web:
    image: nginx:1.18
    ports:
      - "8080:8080"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.prod.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl
    environment:
      - VIRTUAL_HOST=magento.yellowchalk.dev
      - VIRTUAL_PORT=8080
    depends_on:
      - php
      - db

  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile.prod
    volumes:
      - ./src:/var/www/html
    environment:
      - MAGE_RUN_TYPE=website
      - MAGE_RUN_CODE=base
      - MAGE_MODE=production
    depends_on:
      - db

  db:
    image: mysql:8.0
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "127.0.0.1:3306:3306"

  opensearch:
    image: opensearchproject/opensearch:2.11.0
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - plugins.security.disabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9200:9200"
    volumes:
      - osdata:/usr/share/opensearch/data

  redis:
    image: redis:6.2
    volumes:
      - redisdata:/data
    ports:
      - "127.0.0.1:6379:6379"

volumes:
  dbdata:
  esdata:
  redisdata:
  osdata: # This is the missing volume definition
